/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include "gen-cpp/cosim_constants.h"

namespace MMIStandard {

const cosimConstants g_cosim_constants;

cosimConstants::cosimConstants() {
}

} // namespace

