// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include "gen-cpp/MWalkPointEstimationService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::MMIStandard;

class MWalkPointEstimationServiceHandler : virtual public MWalkPointEstimationServiceIf {
 public:
  MWalkPointEstimationServiceHandler() {
    // Your initialization goes here
  }

  void EstimateWalkPoints(std::vector<MWalkPoint> & _return, const std::vector< ::MMIStandard::MSceneObject> & sceneObjects, const  ::MMIStandard::MSceneObject& target, const int32_t amount, const std::map<std::string, std::string> & properties) {
    // Your implementation goes here
    printf("EstimateWalkPoints\n");
  }

};


