/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include "gen-cpp/scene_constants.h"

namespace MMIStandard {

const sceneConstants g_scene_constants;

sceneConstants::sceneConstants() {
}

} // namespace

