/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include "avatar_constants.h"

namespace MMIStandard {

const avatarConstants g_avatar_constants;

avatarConstants::avatarConstants() {
}

} // namespace

