// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include "MCollisionDetectionService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::MMIStandard;

class MCollisionDetectionServiceHandler : virtual public MCollisionDetectionServiceIf {
 public:
  MCollisionDetectionServiceHandler() {
    // Your initialization goes here
  }

  void ComputePenetration( ::MMIStandard::MVector3& _return, const  ::MMIStandard::MCollider& colliderA, const  ::MMIStandard::MTransform& transformA, const  ::MMIStandard::MCollider& colliderB, const  ::MMIStandard::MTransform& transformB) {
    // Your implementation goes here
    printf("ComputePenetration\n");
  }

  bool CausesCollision(const  ::MMIStandard::MCollider& colliderA, const  ::MMIStandard::MTransform& transformA, const  ::MMIStandard::MCollider& colliderB, const  ::MMIStandard::MTransform& transformB) {
    // Your implementation goes here
    printf("CausesCollision\n");
  }

};


