// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include "MGraspPoseService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::MMIStandard;

class MGraspPoseServiceHandler : virtual public MGraspPoseServiceIf {
 public:
  MGraspPoseServiceHandler() {
    // Your initialization goes here
  }

  void GetGraspPoses(std::vector< ::MMIStandard::MGeometryConstraint> & _return, const  ::MMIStandard::MAvatarPostureValues& posture, const  ::MMIStandard::MJointType::type handType, const  ::MMIStandard::MSceneObject& sceneObject, const bool repositionHand) {
    // Your implementation goes here
    printf("GetGraspPoses\n");
  }

};

