/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include "mmu_constants.h"

namespace MMIStandard {

const mmuConstants g_mmu_constants;

mmuConstants::mmuConstants() {
}

} // namespace

